import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link className=" m-3" href='/'>Home</Link>
        <Link className=" m-3" href='/perfomance'>Perfomance</Link>
        <Link className=' m-3' href='/reliability'>Reliability</Link>
        <Link className=' m-3' href='/scale'>Scale</Link>
        {children}
      </body>
    </html>
  )
}
